'use client'

import { useEffect, useRef } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { X, Download, Copy, CheckCircle } from 'lucide-react'
import { useState } from 'react'

interface PRDViewerProps {
  prd: string
  onClose: () => void
}

export default function PRDViewer({ prd, onClose }: PRDViewerProps) {
  const [copied, setCopied] = useState(false)
  const overlayRef = useRef<HTMLDivElement>(null)

  // Close on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [onClose])

  // Close on overlay click
  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === overlayRef.current) onClose()
  }

  const handleCopy = async () => {
    await navigator.clipboard.writeText(prd)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([prd], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `PRD-${new Date().toISOString().slice(0, 10)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div
      ref={overlayRef}
      onClick={handleOverlayClick}
      className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"
    >
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-5xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* ── Modal header ── */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 flex-shrink-0 bg-slate-50 rounded-t-2xl">
          <div>
            <h2 className="font-bold text-slate-900 text-lg">Product Requirements Document</h2>
            <p className="text-slate-500 text-xs mt-0.5">Generated by AI Business Analyst · Review and update as needed</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-sm px-3 py-1.5 border border-slate-300 hover:bg-slate-100 rounded-lg transition-colors text-slate-700"
            >
              {copied ? (
                <>
                  <CheckCircle size={14} className="text-emerald-600" />
                  <span className="text-emerald-700">Copied!</span>
                </>
              ) : (
                <>
                  <Copy size={14} />
                  Copy markdown
                </>
              )}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-sm px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors"
            >
              <Download size={14} />
              Download .md
            </button>
            <button
              onClick={onClose}
              className="ml-1 text-slate-400 hover:text-slate-700 p-1.5 hover:bg-slate-200 rounded-lg transition-colors"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* ── PRD content ── */}
        <div className="flex-1 overflow-y-auto px-10 py-8">
          <div className="prd-content max-w-3xl mx-auto">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{prd}</ReactMarkdown>
          </div>
        </div>

        {/* ── Footer ── */}
        <div className="px-6 py-3 border-t border-slate-200 bg-slate-50 rounded-b-2xl flex items-center justify-between flex-shrink-0">
          <p className="text-slate-400 text-xs">
            Review all sections · Fill in any [bracketed placeholders] · Update as the project evolves
          </p>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 text-xs px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors"
          >
            <Download size={12} />
            Download .md
          </button>
        </div>
      </div>
    </div>
  )
}
